server:
    port: 8081

spring:
    application:
        name: ms-user-provider
    cloud:
        zookeeper:
            connect-string: localhost:2181

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
        driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
        url: jdbc:mysql://10.8.0.246:3306/ei_rpt_kitty?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: eiduo
        password: edGdas*h)

