server:
    port: 7001

spring:
    security:
        user:
            name: root
            password: 123456

eureka:
    instance:
        # hostname: localhost       # eureka服务端的实例名称（单节点）
        hostname: eureka7001.com    # eureka服务端的实例名称（集群）
    client:
        register-with-eureka: false # false表示不向注册中心注册自己。
        fetch-registry: false       # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
        service-url:
            # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。（单节点）
#            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
            # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。（集群）
            defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka7002.com:7002/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka7003.com:7003/eureka/
    server:
        enable-self-preservation: false # 关闭 Eureka 的自我保护机制。

