server:
    port: 7000

eureka:
    instance:
        # hostname: localhost       # eureka服务端的实例名称（单节点）
        hostname: eureka7000.com    # eureka服务端的实例名称（集群）
    client:
        register-with-eureka: false # false表示不向注册中心注册自己。
        fetch-registry: false       # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
        service-url:
            # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。（单节点）
            defaultZone: http://eureka7001.com:7001/eureka/                            #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。（集群）
            # 这里有两个 eureka server，分别是 eureka7000.com、eureka7001.com
            # hostname = eureka7000.com 的服务的 defaultZone = http://eureka7001.com:7001/eureka/
            # hostname = eureka7001.com 的服务的 defaultZone = http://eureka7000.com:7000/eureka/
