server:
    port: 8082

spring:
    application:
        name: ms-user-provider
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
        driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
        url: jdbc:mysql://10.8.0.246:3306/ei_rpt_kitty?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: eiduo
        password: edGdas*h)

eureka:
    client:
        register-with-eureka: true   # 表示是否将自己注册进EurekaServer默认为true。
        fetchRegistry: true          # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
        service-url:
#            defaultZone: http://eureka7001.com:7001/eureka
            defaultZone: http://root:123456@eureka7001.com:7001/eureka,http://root:123456@eureka7002.com:7002/eureka,http://root:123456@eureka7003.com:7003/eureka  # 集群版
    instance:
        instance-id: user_service_${server.port} # 多个实例的 instance-id 要唯一
        prefer-ip-address: true
        # 客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
        lease-renewal-interval-in-seconds: 1
        # 服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
        lease-expiration-duration-in-seconds: 2
        hostname: eureka7002.com
